# Generated by Django 4.2.2 on 2023-11-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_desarrollador'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigofinanciero',
            name='fondo_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.fondo'),
        ),
    ]
