# Generated by Django 4.2.2 on 2023-11-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_codigofinanciero_fondo_afectado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigofinanciero',
            name='fondo_afectado',
        ),
    ]
