# Generated by Django 4.2.5 on 2023-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_remove_base_contribuyentes_alicuota_utilizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_contribuyentes',
            options={'verbose_name': 'Contribuyente', 'verbose_name_plural': 'Base de contribuyentes'},
        ),
        migrations.AlterModelOptions(
            name='regimen',
            options={'verbose_name': 'Regimen', 'verbose_name_plural': 'Tabla de regímenes'},
        ),
        migrations.AlterModelOptions(
            name='tabla_alicuotas',
            options={'verbose_name': 'Alicuota', 'verbose_name_plural': 'Tabla de alícuotas'},
        ),
    ]
