# Generated by Django 4.1.7 on 2023-12-01 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escolariodad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstodoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_legajo', models.IntegerField(unique=True)),
                ('ingreso', models.DateField()),
                ('egreso', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_habiles', models.BooleanField(default=False)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.legajo')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Particion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observaciones', models.DateField(blank=True, null=True)),
                ('certificado_foto', models.ImageField(blank=True, null=True, upload_to='certificados/')),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.licencia')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.tipolicencia'),
        ),
        migrations.AddField(
            model_name='legajo',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.oficina'),
        ),
        migrations.AddField(
            model_name='legajo',
            name='particion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.particion'),
        ),
        migrations.AddField(
            model_name='legajo',
            name='superior_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legajos_subalternos', to='recursos_humanos.legajo'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.legajo')),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.relacion')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.tipodedocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.escolariodad')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.legajo')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.tipoestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('altura', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('piso', models.CharField(blank=True, max_length=255, null=True)),
                ('depto', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.legajo')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.localidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cuit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='cuit/cuil')),
                ('sexo', models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('defuncion', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('discapacitado', models.BooleanField(default=False)),
                ('ganancias', models.BooleanField(default=False)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.estodocivil')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.legajo')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.nacionalidad')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.tipodedocumento')),
            ],
        ),
    ]
