# Generated by Django 4.2.5 on 2023-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientosgastos',
            options={'verbose_name': 'Asiento de gasto', 'verbose_name_plural': 'Asientos de gastos'},
        ),
        migrations.AlterModelOptions(
            name='asientosingresos',
            options={'verbose_name': 'Asiento de ingreso', 'verbose_name_plural': 'Asientos de ingresos'},
        ),
        migrations.AlterModelOptions(
            name='proyecciongastos',
            options={'verbose_name': 'Proyeccion de gasto', 'verbose_name_plural': 'Proyecciones de gastos'},
        ),
        migrations.AlterModelOptions(
            name='proyeccioningresos',
            options={'verbose_name': 'Proyeccion de ingreso', 'verbose_name_plural': 'Proyecciones de ingresos'},
        ),
    ]
