# Generated by Django 4.2.2 on 2023-11-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0003_alter_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='documento',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='seguimiento_expedientes.usuario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='en_transito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='seguimiento_expedientes.usuario'),
        ),
    ]
