# Generated by Django 4.2.2 on 2023-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0004_remove_documento_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='recepcion_confirmada',
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_transito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='transferencias',
            field=models.ManyToManyField(blank=True, null=True, to='seguimiento_expedientes.transferencia'),
        ),
    ]
