# Generated by Django 4.2.2 on 2023-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0005_remove_documento_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='transferencias',
            field=models.ManyToManyField(to='seguimiento_expedientes.transferencia'),
        ),
    ]
