# Generated by Django 4.2.2 on 2023-11-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0007_alter_documento_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='seguimiento_expedientes.usuario'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ejercicio',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='seguimiento_expedientes.usuario'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento_expedientes.tipodocumento'),
        ),
    ]
