# Generated by Django 4.2.2 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0008_alter_documento_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
