# Generated by Django 4.2.5 on 2023-12-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_de_ayuda', '0002_remove_comentariosolicutuddeayuda_solicitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicituddeayuda',
            old_name='cometarios',
            new_name='comentarios',
        ),
    ]
