# Generated by Django 4.2.7 on 2023-12-05 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_de_ayuda', '0004_remove_solicituddeayuda_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddeayuda',
            name='fotos',
        ),
        migrations.AddField(
            model_name='comentariosolicutuddeayuda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='comentariosolicutuddeayuda',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FotoSolicutudDeAyuda',
        ),
    ]
