# Generated by Django 4.2.2 on 2023-11-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_apro', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'codigo de aprobacion',
                'verbose_name_plural': 'Codigos de aprobacion',
            },
        ),
        migrations.CreateModel(
            name='CodigoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos financieros',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('emision', models.DateField(blank=True, null=True)),
                ('alta', models.DateField(blank=True, null=True)),
                ('oc', models.CharField(blank=True, max_length=255, null=True)),
                ('ff', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_ejecutora', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto', models.CharField(blank=True, max_length=255, null=True)),
                ('fondo_afectado', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('devengado', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('autorizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('autorizado_fecha', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigofinanciero')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('total_fondo', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
            },
        ),
        migrations.CreateModel(
            name='OrdenDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('registro_pagado', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fechaOp', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'orden de pago',
                'verbose_name_plural': 'Ordenes de pago',
            },
        ),
        migrations.CreateModel(
            name='ProyeccionGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'ENERO'), ('2', 'FEBRERO'), ('3', 'MARZO'), ('4', 'ABRIL'), ('5', 'MAYO'), ('6', 'JUNIO'), ('7', 'JULIO'), ('8', 'AGOSTO'), ('9', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=255)),
                ('ejercicio', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=255)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('prestamo', models.BooleanField(default=False)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.codigofinanciero')),
            ],
            options={
                'verbose_name': 'Proyeccion de gasto',
                'verbose_name_plural': 'Proyecciones de gastos',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('autorizado', models.BooleanField(default=False)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_entrada', to='facturas.codigofinanciero')),
                ('codigo_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_salida', to='facturas.codigofinanciero')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturas.factura')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.prestamo')),
            ],
            options={
                'verbose_name': 'devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='CodigoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('monto_usado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigoaprobacion')),
                ('codigo_financiero', models.ForeignKey(blank=True, default='AFECTADO', null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigofinanciero')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
            ],
            options={
                'verbose_name': 'codigo de usado',
                'verbose_name_plural': 'Codigos de usados',
            },
        ),
        migrations.AddField(
            model_name='codigofinanciero',
            name='fondo_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.fondo'),
        ),
    ]
