# Generated by Django 4.1.7 on 2023-11-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_desarrollador'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoApro', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ordenDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaOp', models.DateField(blank=True, null=True)),
                ('nroFactura', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('autorizado_fecha', models.DateTimeField(blank=True, null=True)),
                ('emision', models.DateField(blank=True, null=True)),
                ('alta', models.DateField(blank=True, null=True)),
                ('nroFactura', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('oc', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('ff', models.CharField(blank=True, max_length=255, null=True)),
                ('unidadEjecutora', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto', models.CharField(blank=True, max_length=255, null=True)),
                ('fondoAfectado', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Devengado', 'Devengado'), ('OP', 'OP'), ('Pago Parcial', 'Pago Parcial'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='codigoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('montoUsado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigoaprobacion')),
                ('codigoFinanciero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
            ],
        ),
    ]
