# Generated by Django 4.2.5 on 2023-10-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_desarrollador'),
        ('facturas', '0002_codigoaprobacion_codigousado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigousado',
            name='codigoFinanciero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero'),
        ),
    ]
