# Generated by Django 4.1.7 on 2023-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_ordendepago_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='devengado',
            field=models.BooleanField(default=False),
        ),
    ]
