# Generated by Django 4.2.2 on 2023-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_devengado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.AddField(
            model_name='factura',
            name='autorizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
