# Generated by Django 4.2.2 on 2023-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_desarrollador'),
        ('facturas', '0004_alter_factura_options_remove_factura_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='devengado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nroFactura',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
