# Generated by Django 4.2.2 on 2023-10-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigousado',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.factura'),
        ),
    ]
