# Generated by Django 4.2.2 on 2023-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_codigoaprobacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='devengado',
            field=models.BooleanField(default=False),
        ),
    ]
