# Generated by Django 4.2.2 on 2023-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_factura_estado_ordendepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendepago',
            name='fechaOp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
