# Generated by Django 4.2.2 on 2023-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_ordendepago_fechaop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Autorizado', 'Autorizado'), ('OP', 'OP'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
    ]
