# Generated by Django 4.2.2 on 2023-11-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_ordendepago_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
