# Generated by Django 4.2.2 on 2023-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_alter_factura_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendepago',
            name='alta',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='emision',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='ff',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='fondoAfectado',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='oc',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ordendepago',
            name='unidadEjecutora',
        ),
    ]
