# Generated by Django 4.2.2 on 2023-11-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_desarrollador'),
        ('facturas', '0009_factura_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendepago',
            name='registro_pagado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='codigousado',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigoaprobacion'),
        ),
        migrations.AlterField(
            model_name='codigousado',
            name='codigo_financiero',
            field=models.ForeignKey(blank=True, default='AFECTADO', null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero'),
        ),
        migrations.AlterField(
            model_name='codigousado',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.factura'),
        ),
    ]
