# Generated by Django 4.2.2 on 2023-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_ordendepago_registro_pagado_alter_codigousado_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendepago',
            name='registro_pagado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
